MANGO_ROOT/MANGO/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls'))
]

MANGO_ROOT/music/urls.py
from django.urls import path
from . import views

app_name = 'Music'

urlpatterns = [
    path('top/', views.top, name='top'),
    path('search/', views.search, name='search'),
    path('searchlist/<track>/', views.searchlist, name='searchlist'),
    path('recommend/<query>/', views.recommend, name='recommend'),
    path('update_data/',views.update_data,name="update"),
]

MANGO_ROOT/user/urls.py
from django.urls import path
from . import views

app_name = 'User'

urlpatterns = [
    path('base/', views.base, name='base'),
    path('index/', views.index, name='index'),
    path('elements/', views.elements, name='elements'),
    path('generic/', views.generic, name='generic'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('join/', views.join, name='join'),
    path('checkid/', views.checkid, name='checkid'),
    path('addPlaylist/', views.addPlaylist, name='addPlaylist'),
    path('getPlaylist/', views.getPlaylist, name='getPlaylist'),
    path('showPlaylist/', views.showPlaylist, name='showPlaylist'),
    path('deletePlaylist/<track>/', views.deletePlaylist, name='deletePlaylist'),
]

MANGO_ROOT/music/models.py
from django.db import models

class Chatbot(models.Model):
    intent = models.IntegerField(verbose_name='의도')
    emotion = models.IntegerField(verbose_name='감정', null=True)
    ner = models.CharField(max_length=100, null=True, verbose_name='개체명')
    answer = models.TextField(verbose_name='대답')
    answer_image = models.CharField(max_length=200, null=True, verbose_name='대답이미지')

    class Meta:
        db_table = 'mango_train_data'
        verbose_name = '챗봇'
        verbose_name_plural = '챗봇(들)'

MANGO_ROOT/music/views.py
from django.http import JsonResponse
from django.shortcuts import render
from matplotlib.pyplot import get
import requests
from bs4 import BeautifulSoup
import base64
import json
from user.views import getLyrics

# 재학습 
import pandas as pd
import os
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator



access_token = 'BQDAP9FCoLE96LUprlBGFHlaIJp0jkZavuJB3_ws7Su7qtt3eIijRHmzzjMUkC-C2SidtBnfy6gguUpottg'

def home(request):
    return render(request, 'home.html')

def top(request):
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36'
    }

    url = "https://www.melon.com/chart/index.htm"
    melons = [
        {
            'track': song.select_one(' div.wrap div.wrap_song_info .rank01 a').text.strip(),
            'album': song.select_one(' div.wrap div.wrap_song_info .rank03 a').text.strip(),
            'image': song.select_one('div.wrap a.image_typeAll > img')['src'].strip(),
            'artist': song.select_one(' div.wrap div.wrap_song_info .rank02 a').text.strip()
        }
        for song in BeautifulSoup(requests.get(url, headers=headers).text, 'html.parser').select('div.d_song_list table tbody tr')
    ]
    return render(request, 'top.html', {'melons': melons})

def search(request):
    global access_token
    type = request.GET.get('type')
    item = request.GET.get('item')

    context = {}
    try:
        if type=='album':
            artistget = request.GET.get('artist')
            melon_data = getMelonAlbum(item, artistget)
            print(melon_data)
            context['image'] = melon_data['image']
            context['image_small'] = melon_data['image_small']
            context['name'] = melon_data['name']
            context['artist'] = melon_data['artist']
            context['tracks'] = melon_data['tracks']
        elif type=='artist':
            melon_data = getMelonArtist(item)
            print(melon_data)
            context['image'] = melon_data['image']
            context['name'] = melon_data['name']
            context['tracks'] = melon_data['tracks']
        elif type=='track':
            artistget = request.GET.get('artist')
            melon_data = getMelonInfo(item, artistget)
            context['album'] = melon_data['album']
            context['release'] = melon_data['release']
            context['image'] = melon_data['image']
            context['name'] = melon_data['name']
            context['artist'] = melon_data['artist']
            context['artists'] = melon_data['artist']
            context['lyrics'] = melon_data['lyrics']
    except IndexError as ie:
        context['error'] = 'IndexError'

    return render(request, f'{type}.html',{'data': context})

def recommend(request, query):
    return JsonResponse({'data': query})

def getMelonInfo(track, artist):
    track2 = track.replace('953964', '&amp;')
    query = f'{track2} {artist}'

    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36'
    }
    q_url = 'https://www.melon.com/search/song/index.htm?q='+query
    try:
        trackid = BeautifulSoup(requests.get(q_url, headers=headers).text, 'html.parser').select_one('table tbody tr td div.wrap.pd_none.left input')['value']
        url = 'https://www.melon.com/song/detail.htm?songId='+trackid
        soup = BeautifulSoup(requests.get(url, headers=headers).text, 'html.parser')
        data = {
            'album': soup.select_one('dl.list > dd').text.strip(),
            'release': soup.select('dl.list > dd')[1].text.strip(),
            'image': soup.select_one('div.wrap_info > div.thumb > a > img')['src'].strip(),
            'name': soup.select_one('div.info > div.song_name').text.replace('곡명', '').strip(),
            'artist': soup.select_one('div.info > div.artist > a.artist_name > span').text.strip(),
            'lyrics': BeautifulSoup(str(soup.select_one('#d_video_summary')).replace('<br/>', '\n'), 'html.parser').text.split('\n'),
            }
    except Exception as e:
        return ('곡 정보 불러오기 실패', e)
    return data

def getMelonArtist(artist):
    q_url = 'https://www.melon.com/search/artist/index.htm?q='+artist
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36'
    }
    data = {}
    try:
        artistid = BeautifulSoup(requests.get(q_url, headers=headers).text, 'html.parser').select_one('#pageList .d_artist_list ul li .wrap_atist12 button.btn_join_fan')['data-artist-no']
        url = f"https://www.melon.com/artist/song.htm?artistId={artistid}#params%5BorderBy%5D=POPULAR_SONG_LIST&params%5B"
        soup = BeautifulSoup(requests.get(url, headers=headers).text, 'html.parser')
        data['image'] = soup.select_one('#artistImgArea img').get('src')
        data['name'] = soup.select_one('.title_atist').text.replace('아티스트명', '')
        data['tracks'] = [{
            'title': tr.select_one('.ellipsis a.fc_gray').text,
            'artist': tr.select_one('#artistName a.fc_mgray').text,
            'album': tr.select_one('.ellipsis:not(#artistName) a.fc_mgray').text,
        }
        for tr in soup.select('#frm div.tb_list.d_song_list.songTypeOne table tbody tr')]
    except Exception as e:
        return ('아티스트 정보 불러오기 실패', e)
    return data


def getMelonAlbum(album, artist):
    album2 = album.replace('953964', '&amp;')
    query = f'{album2} {artist}'

    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36'
    }
    q_url = 'https://www.melon.com/search/album/index.htm?q='+query
    try:
        soup = BeautifulSoup(requests.get(q_url, headers=headers).text, 'html.parser').select_one('#frm ul.album11_ul li.album11_li div.wrap_album04')
        albumid = soup.select_one('dd.wrap_btn > a')['data-album-no']
        albumsoup = BeautifulSoup(requests.get('https://www.melon.com/album/detail.htm?albumId='+albumid, headers=headers).text, 'html.parser')
        data = {}
        data['image'] = soup.select_one('a.thumb > img')['src'].strip()
        data['image_small'] = soup.select_one('a.thumb > img')['src'].replace('/260/', '/120/').strip()
        data['name'] = soup.select_one('div.atist_info > dl > dt > a.ellipsis').text.strip()
        data['artist'] = soup.select_one('div.atist_info dd.atistname > div.ellipsis > a').text.strip()
        data['tracks'] = [{
            'name': tr.select_one('div.wrap_song_info div.ellipsis span a').text.strip(),
            'artist': tr.select_one('div.wrap_song_info div.ellipsis.rank02 a').text.strip(),
            } for tr in albumsoup.select('#frm table tbody tr:not(.cd)')]
    except Exception as e:
        return ('앨범 정보 불러오기 실패', e, data)
    return data

def searchlist(request, track):
    context = {}
    headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36'
    }
    print(track+'로 음악 검색')
    url = "https://www.melon.com/search/total/index.htm?q="+track
    soup = BeautifulSoup(requests.get(url, headers=headers).text, 'html.parser')
    # 아티스트 있는지 확인
    artistsoup = soup.select_one('.section_atist div.wrap_cntt.clfix.d_artist_list')
    if artistsoup and artistsoup.select_one('a.wrap_thumb > img'):
        context['artist'] = {
            'image': soup.select_one('a.wrap_thumb > img').get('src'),
            'name': soup.select_one('.atist_dtl_info .fc_serch').text.strip(),
            }
    context['tracks'] = [
                            {
                                'track': BeautifulSoup(str(searchs.select_one('td div.ellipsis a.fc_gray')).replace('<b>','').replace('</b>',""), 'html.parser').text,
                                'artist': searchs.select_one('#artistName span').text,
                            }
                            for searchs in soup.select('#frm_searchSong table tbody tr')
                        ][:3]

    return JsonResponse({'data': context})

def update_data(request):
    query = request.GET.get('query')
    intent = request.GET.get('intent')
    data = pd.DataFrame([query],columns = ['sentence'])
    data['label'] = intent
    print("===================",query,intent,"=================================")
    retrain_file = 'static/retrain_data/retrain_data.csv'
    try:
        retrain_data = pd.read_csv(retrain_file)
    except:
        data.to_csv(r'./static/retrain_data/retrain_data.csv')
        context = {'data':"성공"}
        return JsonResponse(context)
  
    result = pd.concat([retrain_data,data])
    result.to_csv(r'./static/retrain_data/retrain_data.csv',index=False)
    context = {'data':"성공"}

    return JsonResponse(context)

MANGO_ROOT/music/templates/album.html
<link rel="stylesheet" href="/static/assets/css/main.css"/>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Dongle&display=swap" rel="stylesheet">
<script src="https://kit.fontawesome.com/c0bcdc1f96.js" crossorigin="anonymous"></script>
<div id="one">
    <div class="wrapper special" style='padding-top:3%;'>
        <a href="{% url 'Music:top' %}" class="button primary icon solid fa-arrow-left" style='float:left;position:fixed;left: 3%;opacity: 0.8;'>Top100</a>
        <div style='clear:both;'></div>
        <div class="inner">
            <header class="major">
                <h2>앨범 정보</h2>
            </header>
            <img src="{{data.image}}" alt="앨범 커버">
            <h3>{{data.name}}</h3>
            <h4>{{data.artist}}</h4>
            <div class="table-wrapper">
                <table class="alt">
                    <thead>
                        <tr>
                            <th></th>
                            <th>title</th>
                            <th>album</th>
                            <th>artist</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for track in data.tracks %}
                        <tr>
                            <td><a href='{% url "Music:search" %}?type=album&item={{data.name}}&artist={{data.artist}}'><img src="{{data.image_small}}" alt="{{data.name}}"></a></td>
                            <td><a href='{% url "Music:search" %}?type=track&item={{track.name}}&artist={{data.artist}}'>{{track.name}}</a></td>
                            <td><a href='{% url "Music:search" %}?type=album&item={{data.name}}&artist={{data.artist}}'>{{data.name}}</a></td>
                            <td><a href='{% url "Music:search" %}?type=artist&item={{data.artist}}'>{{data.artist}}</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<script src="/static/assets/js/jquery.min.js"></script>
<script src="/static/assets/js/jquery.dropotron.min.js"></script>
<script src="/static/assets/js/browser.min.js"></script>
<script src="/static/assets/js/breakpoints.min.js"></script>
<script src="/static/assets/js/util.js"></script>
<script src="/static/assets/js/main.js"></script>
<style>
    td{
        vertical-align: middle;
    }
    td:hover{
        background-color: rgba(0,0,0,0.2);
    }
</style>
<style>
    body::-webkit-scrollbar {
        width: 10px;  /* 스크롤바의 너비 */
    }
    
    body::-webkit-scrollbar-thumb {
        height: 30%; /* 스크롤바의 길이 */
        background: rgba(255, 139, 119, 0.6); /* 스크롤바의 색상 */
        
        border-radius: 10px;
    }

    body::-webkit-scrollbar-track {
        background: rgba(33, 122, 244, .0);  /*스크롤바 뒷 배경 색상*/
    }
    div.box > h3 {
        border-bottom: 2px solid #ff8b77;
    }
</style>

MANGO_ROOT/music/templates/artist.html
<link rel="stylesheet" href="/static/assets/css/main.css"/>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Dongle&display=swap" rel="stylesheet">
<script src="https://kit.fontawesome.com/c0bcdc1f96.js" crossorigin="anonymous"></script>
<div id="one">
    <div class="wrapper special" style='padding-top:3%;'>
        <a href="{% url 'Music:top' %}" class="button primary icon solid fa-arrow-left" style='float:left;position:fixed;left: 3%;opacity: 0.8;'>Top100</a>
        <div style='clear:both;'></div>
        <div class="inner">
            <header class="major">
                <h2>아티스트 정보</h2>
            </header>
            <img src="{{data.image}}" alt="앨범 커버">
            <h3>{{data.name}}</h3>
            <div class="table-wrapper">
                <h4>인기곡</h4>
                <table class="alt">
                    <thead>
                        <tr>
                            <th>title</th>
                            <th>album</th>
                            <th>artist</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for track in data.tracks %}
                        <tr>
                            <!-- ['album']['images'][1]['url'] -->
                            <td><a href='{% url "Music:search" %}?type=track&item={{track.title}}&artist={{data.name}}'>{{track.title}}</a></td>
                            <td><a href='{% url "Music:search" %}?type=album&item={{track.album}}&artist={{data.name}}'>{{track.album}}</a></td>
                            <td><a href='{% url "Music:search" %}?type=artist&item={{data.name}}'>{{data.name}}</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<script src="/static/assets/js/jquery.min.js"></script>
<script src="/static/assets/js/jquery.dropotron.min.js"></script>
<script src="/static/assets/js/browser.min.js"></script>
<script src="/static/assets/js/breakpoints.min.js"></script>
<script src="/static/assets/js/util.js"></script>
<script src="/static/assets/js/main.js"></script>
<style>
    td{
        vertical-align: middle;
    }
    td:hover{
        background-color: rgba(0,0,0,0.2);
    }
</style>
<style>
    body::-webkit-scrollbar {
        width: 10px;  /* 스크롤바의 너비 */
    }
    
    body::-webkit-scrollbar-thumb {
        height: 30%; /* 스크롤바의 길이 */
        background: rgba(255, 139, 119, 0.6); /* 스크롤바의 색상 */
        
        border-radius: 10px;
    }

    body::-webkit-scrollbar-track {
        background: rgba(33, 122, 244, .0);  /*스크롤바 뒷 배경 색상*/
    }
    div.box > h3 {
        border-bottom: 2px solid #ff8b77;
    }
</style>

MANGO_ROOT/music/templates/top.html
<link rel="stylesheet" href="/static/assets/css/main.css"/>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Dongle&display=swap" rel="stylesheet">
<div id="one">
    <div class="wrapper special">
        <div class="inner">
            <header class="major">
                <h2>Top 100</h2>
            </header>
            <div class="table-wrapper">
                <table class="alt">
                    <thead>
                        <tr>
                            <th></th>
                            <th>title</th>
                            <th>album</th>
                            <th>artist</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for song in melons %}
                        <tr>
                            <td><a href='{% url "Music:search" %}?type=album&item={{song.album}}&artist={{song.artist}}'><img src="{{song.image}}" alt="{{song.album}}"></a></td>
                            <td><a href='{% url "Music:search" %}?type=track&item={{song.track}}&artist={{song.artist}}'>{{song.track}}</a></td>
                            <td><a href='{% url "Music:search" %}?type=album&item={{song.album}}&artist={{song.artist}}'>{{song.album}}</a></td>
                            <td><a href='{% url "Music:search" %}?type=artist&item={{song.artist}}'>{{song.artist}}</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script src="/static/assets/js/jquery.min.js"></script>
<script src="/static/assets/js/jquery.dropotron.min.js"></script>
<script src="/static/assets/js/browser.min.js"></script>
<script src="/static/assets/js/breakpoints.min.js"></script>
<script src="/static/assets/js/util.js"></script>
<script src="/static/assets/js/main.js"></script>
<style>
    td{
        vertical-align: middle;
    }
    td:hover{
        background-color: rgba(0,0,0,0.2);
    }
</style>
<style>
    body::-webkit-scrollbar {
        width: 10px;  /* 스크롤바의 너비 */
    }
    
    body::-webkit-scrollbar-thumb {
        height: 30%; /* 스크롤바의 길이 */
        background: rgba(255, 139, 119, 0.6); /* 스크롤바의 색상 */
        
        border-radius: 10px;
    }

    body::-webkit-scrollbar-track {
        background: rgba(33, 122, 244, .0);  /*스크롤바 뒷 배경 색상*/
    }
</style>

MANGO_ROOT/music/templates/track.html
<link rel="stylesheet" href="/static/assets/css/main.css"/>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Dongle&display=swap" rel="stylesheet">
<script src="https://kit.fontawesome.com/c0bcdc1f96.js" crossorigin="anonymous"></script>
<div id="one">
    <div class="wrapper special" style='padding-top:3%;'>
        <a href="{% url 'Music:top' %}" class="button primary icon solid fa-arrow-left" style='float:left;position:fixed;left: 3%;opacity: 0.8;'>Top100</a>
        <div style='clear:both;'></div>
        <div class="inner">
            <header class="major">
                {% if data.error == "IndexError" %}
                <h2>곡 정보 찾기를 실패했습니다.</h2>
                {% else %}
                <h2>곡 정보</h2>
                {% endif %}
            </header>
            <img src="{{data.image}}" alt="앨범 커버">
            <h2 class='name'>{{data.name}}</h2>
            <a href="javascript:youtube(true);" class="button primary fit small" style='margin-bottom: 1%;'><i class='fa-solid fa-play' style='margin-right: 1%;'></i>PLAY</a>
            <a href="javascript:youtube(false);" class="button fit small" style='margin-bottom: 3%;'><i class='fa-solid fa-plus' style='margin-right: 1%;'></i>ADD PLAYLIST</a>
            <div class="box">
                <h3>아티스트</h3>
                <a href='{% url "Music:search" %}?type=artist&item={{data.artist}}' class='artists'><h4>{{data.artist}}</h4></a>
                <h3>앨범</h3>
                <a href='{% url "Music:search" %}?type=album&item={{data.album}}&artist={{data.artists.0.name}}'><h4>{{data.album}}</h4></a>
                <h3>발매</h3>
                <p>{{data.release}}</p>
                <h3>가사</h3>
                <div style='text-align:left;'>
                {% for lyric in data.lyrics %}
                <p style='margin:0;min-height:3%;'>{{lyric}}</p>
                {% endfor %}
                </div>
            </div>
        </div>
    </div>

</div>
<script src="/static/assets/js/jquery.min.js"></script>
<script src="/static/assets/js/jquery.dropotron.min.js"></script>
<script src="/static/assets/js/browser.min.js"></script>
<script src="/static/assets/js/breakpoints.min.js"></script>
<script src="/static/assets/js/util.js"></script>
<script src="/static/assets/js/main.js"></script>
<style>
    td{
        vertical-align: middle;
    }
    td:hover{
        background-color: rgba(0,0,0,0.2);
    }
</style>
<style>
    body::-webkit-scrollbar {
        width: 10px;  /* 스크롤바의 너비 */
    }
    
    body::-webkit-scrollbar-thumb {
        height: 30%; /* 스크롤바의 길이 */
        background: rgba(255, 139, 119, 0.6); /* 스크롤바의 색상 */
        
        border-radius: 10px;
    }

    body::-webkit-scrollbar-track {
        background: rgba(33, 122, 244, .0);  /*스크롤바 뒷 배경 색상*/
    }
    div.box > h3 {
        border-bottom: 2px solid #ff8b77;
    }
</style>
<script>
    api_key = 'AIzaSyD-MlnJmv8El7gQLdQNALcPxlmOgXkuBMY'
    function youtube(play){
        name = $('h2.name').text()
        artist = $('.artist').text()
        $.ajax({
            url: `https://www.googleapis.com/youtube/v3/search?part=snippet&q=${artist} ${name}&type=video&key=`+api_key,
            datatype:'json',
            success:function(response){
                var videoId = response.items[0].id.videoId
                dataname = name.replace('&', '953964')
                $.ajax({
                    url: ("{% url 'User:addPlaylist' %}?youtube=12345&track="+dataname+"&artist="+artist).replace(/12345/, videoId.toString()),
                    datatype:'json',
                    success:function(response){
                        if(play){
                            window.parent.document.querySelector('#player').src = 'https://www.youtube.com/embed?autoplay=1&playlist='+response.data+'&autoplay=1&loop=1'
                            // 띄우기
                            if($(window.parent.document.querySelector('#playerdiv')).css('display')=='none'){
                                $(window.parent.document.querySelector('#playerdiv')).slideToggle()
                             }
                        }else{
                            alert(dataname+' 을 플레이리스트에 추가했습니다!')
                        }
                    }
                })
            }
        })
    }
</script>