MANGO_ROOT/MANGO/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls'))
]

MANGO_ROOT/user/urls.py
from django.urls import path
from . import views

app_name = 'User'

urlpatterns = [
    path('base/', views.base, name='base'),
    path('index/', views.index, name='index'),
    path('elements/', views.elements, name='elements'),
    path('generic/', views.generic, name='generic'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('join/', views.join, name='join'),
    path('checkid/', views.checkid, name='checkid'),
    path('addPlaylist/', views.addPlaylist, name='addPlaylist'),
    path('getPlaylist/', views.getPlaylist, name='getPlaylist'),
    path('showPlaylist/', views.showPlaylist, name='showPlaylist'),
    path('deletePlaylist/<track>/', views.deletePlaylist, name='deletePlaylist'),
]

MANGO_ROOT/user/models.py
from django.db import models

class User(models.Model):
    userid = models.CharField(max_length=20, verbose_name='아이디')
    password = models.CharField(max_length=500, verbose_name='비밀번호')

    class Meta:
        db_table = 'MANGO_user'
        verbose_name = '유저'
        verbose_name_plural = '유저(들)'

    def __str__(self):
        return f'id{self.id}.{self.userid}'

class Music_prefer(models.Model):
    user = models.ForeignKey('user.User', on_delete=models.CASCADE)
    preference = models.CharField(max_length=50, verbose_name='음악 분위기')

    class Meta:
        db_table = 'MANGO_music_prefer'
        verbose_name = '선호 음악 분위기'
        verbose_name_plural = '선호 음악 분위기(들)'


# class Like_song(models.Model):
#     userpk = models.ForeignKey('user.User', on_delete=models.CASCADE)
#     song_num = models.IntegerField(verbose_name='곡 번호')

#     class Meta:
#         db_table = 'MANGO_like_song'

class Playlist(models.Model):
    user = models.ForeignKey('user.User', on_delete=models.CASCADE)
    youtube = models.CharField(max_length=200, verbose_name='유튜브url')
    track = models.CharField(max_length=200, verbose_name='제목')
    artist = models.CharField(max_length=200, verbose_name='아티스트')
    lyrics = models.TextField(verbose_name='가사')
    order = models.IntegerField(default=0, verbose_name = '곡 순서')

    class Meta:
        db_table = 'MANGO_playlist'
        verbose_name = '플레이리스트'
        verbose_name_plural = '플레이리스트(들)'

    def __str__(self):
        return self.user.userid + '의 곡'

MANGO_ROOT/user/forms.py
from django import forms
from user.models import User

class LoginForm(forms.Form):
    userid = forms.CharField(
        error_messages={
            'required' : '아이디를 입력해주세요'
        },
        max_length=20,label='아이디'
    )
    password = forms.CharField(
        error_messages={
            'required' : '비밀번호를 입력해주세요'
        },
        widget=forms.PasswordInput,max_length=100,label='비밀번호'
    )


    def clean(self):
        cleaned_data = super().clean()

        self.userid = cleaned_data.get('userid')
        self.password = cleaned_data.get('password')

class JoinForm(forms.ModelForm):
    password = forms.CharField(
        error_messages={
            'required' : '비밀번호를 입력해주세요'
        },
        widget=forms.PasswordInput,max_length=500,label='비밀번호'
    )

    re_password = forms.CharField(
        error_messages={
            'required' : '비밀번호를 입력해주세요'
        },
        widget=forms.PasswordInput,max_length=500,label='비밀번호 확인'
    )

    # 취향
    prefer = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=enumerate(['슬픔', '감사', '걱정', '중립', '기쁨', '분노', '여유', '스트레스', '신남', '실망',
       '외로운', '우울함', '편안']), label='음악 취향')
    
    class Meta:
        model = User
        fields = '__all__'

    def clean(self):   
        # 우선 부모 Form 의 clean() 수행 --> 값이 들어있지 않으면 error 처리 
        cleand_data = super().clean()
        
        self.userid = cleand_data.get('userid')
        self.password = cleand_data.get('password')
        self.prefer = cleand_data.get('prefer')

MANGO_ROOT/user/views.py
from gc import get_objects
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.hashers import make_password, check_password
import requests
import json
from bs4 import BeautifulSoup
from sympy import re
from .forms import LoginForm, JoinForm
from .models import Music_prefer, Playlist, User

def base(request):
    return render(request, 'base.html')

def index(request):
    return render(request, 'index.html')

def elements(request):
    return render(request, 'elements.html')

def generic(request):
    return render(request, 'generic.html')

def login(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    elif request.method == 'POST':
        userid = request.POST.get('userid', None)
        password = request.POST.get('password', None)

        res_data = {}

        if not(userid and password):  # 값이 다 입력되었는지 확인
            res_data['error'] = '모든 값을 입력해야 합니다'
        else:
            # 모델로부터 데이터를 가져와야 한다
            user = User.objects.get(userid=userid)
            # 비밀번호 비교
            if check_password(password, user.password):
                # 로그인 처리 (세션 사용)
                request.session['user'] = {'id': user.id, 'userid': user.userid}
                request.session['playlist'] = ",".join([track.youtube for track in Playlist.objects.filter(user=user).order_by('-id')])
                request.session['playlist_info'] = json.dumps({str(i):{'track': track.track, 'artist': track.artist, 'lyrics': track.lyrics} for i, track in enumerate(Playlist.objects.filter(user=user).order_by('-id'))}, ensure_ascii=False)
                return redirect('/')   # 로그인 성공후 home 으로 redirect
            else:
                # 비밀번호 불일치.  로그인 실패 처리
                res_data['error'] = '비밀번호를 틀렸습니다'

        return render(request, 'login.html', res_data)

def logout(request):
    if request.session.get('user'):
        del(request.session['user'])
    return redirect('/')

def join(request):
    # 회원가입 처리
    if request.method=="POST":
        form = JoinForm(request.POST)
        moods = ['슬픔', '감사', '걱정', '중립', '기쁨', '분노', '여유', '스트레스', '신남', '실망', '외로운', '우울함', '편안']
        if form.is_valid():
            user = User(
                userid = form.userid,
                password = make_password(form.password),
            )
            user.save()

            for pk in form.prefer:
                Music_prefer(
                    user=user,
                    preference=moods[int(pk)],
                ).save()
        else: 
            print("join 실패")
        return redirect("/user/login/")
    else:
        form = JoinForm()
        return render(request,'join.html',{'form':form})

def checkid(request):
    userid = request.GET.get('userid')
    context={}
    try:
        User.objects.get(userid=userid)
    except:
        context['data'] = "not exist" # 아이디 중복 없음

    return JsonResponse(context)

def addPlaylist(request):
    if request.session['user']:
        userid = request.session['user']['id']
    else:
        return JsonResponse({'data': 'nologin'})

    youtube = request.GET.get('youtube')
    track = request.GET.get('track')
    artist = request.GET.get('artist')
    lyrics = getLyrics(track, artist)

    play = Playlist(user=get_object_or_404(User, id=userid), youtube=youtube, track=track, artist=artist, lyrics=lyrics)
    play.save()
    request.session['playlist'] = ",".join([track.youtube for track in Playlist.objects.filter(user=userid).order_by('-id')])
    request.session['playlist_info'] = json.dumps({str(i):{"track": track.track, "artist": track.artist, "lyrics": track.lyrics} for i, track in enumerate(Playlist.objects.filter(user=userid).order_by('-id'))}, ensure_ascii=False)
    return JsonResponse({'data': request.session['playlist']})

def getLyrics(track, artist):
    track2 = track.replace('953964', '&amp;')
    query = f'{track2} {artist}'

    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36'
    }
    q_url = 'https://www.melon.com/search/song/index.htm?q='+query
    try:
        trackid = BeautifulSoup(requests.get(q_url, headers=headers).text, 'html.parser').select_one('table tbody tr td div.wrap.pd_none.left input')['value']
        url = 'https://www.melon.com/song/popup/lyricPrint.htm?songId='+trackid
        temp_lyrics =  str(BeautifulSoup(requests.get(url, headers=headers).text, 'html.parser').select_one('.box_lyric_text')).replace('<div class="box_lyric_text">', '').replace('</div>', '').replace('\r', '').replace('\n', '').replace('\t', '').split('<br/>')
    except Exception as e:
        return '가사 불러오기 실패'
    return "\n".join(temp_lyrics)

def getPlaylist(request):
    if request.session['user']:
        userid = request.session['user']['id']
    else:
        return JsonResponse({'data': 'nologin'})

    return JsonResponse({'playlist': ",".join([track.youtube for track in Playlist.objects.filter(user=userid).order_by('-id')])})

def showPlaylist(request):
    if request.session['user']:
        userid = request.session['user']['id']
    else:
        return JsonResponse({'data': 'nologin'})

    context = [
        {
            'youtube': play.youtube,
            'track': play.track,
            'artist': play.artist,
        }
        for play in Playlist.objects.filter(user=userid).order_by('-id')
    ]
    return JsonResponse({'playlist': context})

def deletePlaylist(request, track):
    if request.session['user']:
        userid = request.session['user']['id']
    cnt = False
    try:
        playlist = Playlist.objects.filter(user=userid).order_by('-id')
        for tr in playlist:
            if tr.track.replace(" ", "") == track.replace(" ", ""):
                tr.delete()
                cnt = True
        
        if cnt:
            return JsonResponse({'data': 'success'})
        else:
            return JsonResponse({'data': 'fail'})

    except Exception as e:
        return JsonResponse({'data': 'fail'})

MANGO_ROOT/user/templates/base.html
<!DOCTYPE HTML>
<!--
	Inverse by Pixelarity
	pixelarity.com | hello@pixelarity.com
	License: pixelarity.com/license
-->
<html lang='kor'>
	<head>
		<title>{% block title %}{% endblock  %}</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<link rel="stylesheet" href="/static/assets/css/main.css"/>
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Dongle&display=swap" rel="stylesheet">
		<script src="https://kit.fontawesome.com/c0bcdc1f96.js" crossorigin="anonymous"></script>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
		{% comment %} <script src="/static/chat.js"></script> {% endcomment %}
	</head>
	<body class="is-preload">

		<!-- Header -->
			<header id="header" class="alt" style='padding:1rem;'>
				<a style='display:flex;' class="logo" href="/"><img width='45' height='45' src="/static/images/MANGO.png" alt='MANGO'><p style='margin: auto;'>MANGO</p></a>
				<nav id="nav">
					<ul>
						{% if request.session.user %}
							<li>
								<a class="dropdown">{{request.session.user.userid}}</a>
								<ul>
									<li><a href="{% url 'User:logout' %}">logout</a></li>
								</ul>
							</li>
						{% else %}
							<li><a href="{% url 'User:login' %}">Login</a></li>
						{% endif %}
					</ul>
				</nav>
			</header>
			{% block banner %}{% endblock  %}

            {% block contents %}{% endblock  %}


		<!-- Footer -->
			<div id="footer">
				<div class="wrapper style2">
					<div class="inner">
						<header class="major">
							<h2>MANGO <sub>by</sub><strong>어무해</strong></h2>
						</header>
						<div class="content">
							<ul class="icons" style='width: 100%;'>
								<li>
									<span class="icon solid fa-star"></span>
									<div>
										<strong>조동건</strong>
									</div>
								</li>
								<li>
									<span class="icon solid fa-star"></span>
									<div>
										<strong>김정현</strong>
									</div>
								</li>
								<li>
									<span class="icon solid fa-star"></span>
									<div>
										<strong>김혜원</strong>
									</div>
								</li>
								<li>
									<span class="icon solid fa-star"></span>
									<div>
										<strong>이정수</strong>
									</div>
								</li>
								<li style='margin: 0 5px;'>
									<span class="icon solid fa-star"></span>
									<div>
										<strong>이창준</strong>
									</div>
								</li>
							</ul>
						</div>
					</div>
					<div class="copyright">
						&copy; Korea IT academy. All rights reserved. Lorem ipsum dolor sit amet.
					</div>
				</div>
			</div>

		<!-- Scripts -->
			<script src="/static/assets/js/jquery.min.js"></script>
			<script src="/static/assets/js/jquery.dropotron.min.js"></script>
			<script src="/static/assets/js/browser.min.js"></script>
			<script src="/static/assets/js/breakpoints.min.js"></script>
			<script src="/static/assets/js/util.js"></script>
			<script src="/static/assets/js/main.js"></script>

	</body>
	{% block script %}{% endblock  %}
	<style>
		ul.icons{
			width: 100%;
			display: flex;
			justify-content: center;
		}
		
		ul.icons li{
			display: inline-block;
			float: left;
			height: 100%;
			width: 33%;
			margin: 0 5px;
		}
	</style>
</html>

MANGO_ROOT/user/templates/generic.html
<!DOCTYPE HTML>
<!--
	Inverse by Pixelarity
	pixelarity.com | hello@pixelarity.com
	License: pixelarity.com/license
-->
<html>
	<head>
		<title>Untitled</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<link rel="stylesheet" href="/static/assets/css/main.css" />
	</head>
	<body class="is-preload">

		<!-- Header -->
			<header id="header">
				<a class="logo" href="index.html">Inverse <span>by Pixelarity</span></a>
				<nav id="nav">
					<ul>
						<li class="current"><a href="index.html">Home</a></li>
						<li>
							<a href="#" class="dropdown">Dropdown</a>
							<ul>
								<li><a href="#">Option One</a></li>
								<li><a href="#">Option Two</a></li>
								<li><a href="#">Option Three</a></li>
								<li>
									<a href="#">Submenu</a>
									<ul>
										<li><a href="#">Option One</a></li>
										<li><a href="#">Option Two</a></li>
										<li><a href="#">Option Three</a></li>
										<li><a href="#">Option Four</a></li>
									</ul>
								</li>
							</ul>
						</li>
						<li><a href="generic.html">Generic</a></li>
						<li><a href="elements.html">Elements</a></li>
					</ul>
				</nav>
			</header>

		<!-- One -->
			<div id="main">
				<div class="wrapper">
					<div class="inner">
						<header class="major">
							<h1>Generic</h1>
							<p>Elit massa nisl elementum lorem ipsum dolor sit consequat</p>
						</header>
						<div class="image main">
							<img src="images/pic01.jpg" alt="" />
						</div>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin scelerisque vehicula eros at condimentum. Pellentesque massa nisl, elementum id mi sed, aliquam gravida diam. Donec condimentum eros magna, ut convallis nunc lacinia ac. Sed pellentesque ante nec pharetra facilisis. Nullam sagittis ullamcorper feugiat. Maecenas sollicitudin tincidunt convallis. Suspendisse vel arcu vitae quam pretium interdum. Sed id felis id enim maximus rutrum quis vitae mauris. Nulla facilisi. Integer pharetra mi diam, at viverra neque tristique vitae. Nunc interdum ipsum porta suscipit sagittis. Nam tempor eros non lorem consequat, vel euismod mi hendrerit. Ut suscipit lacus varius risus finibus faucibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>
						<p>Sed auctor, erat nec tristique aliquam, turpis elit iaculis nunc, et suscipit est orci sit amet orci. Nam lacus nunc, suscipit sit amet purus non, imperdiet lacinia lorem. Nunc posuere ligula sit amet massa auctor feugiat. Nam sed odio ac mauris venenatis molestie et ac enim. Etiam rhoncus libero eros, at bibendum elit molestie in. Quisque lacinia, eros nec elementum dictum, est tellus feugiat tellus, quis volutpat quam massa eget nibh. Maecenas elementum euismod ornare. Duis porttitor feugiat mauris in volutpat. Nam ac nisl vulputate, finibus orci lacinia, facilisis lectus. Nulla diam lorem, dignissim vel laoreet imperdiet, bibendum in felis. Duis porttitor accumsan diam, non venenatis est. Nunc et maximus augue, sit amet convallis est. Sed sed magna justo. Sed sagittis consequat metus, eu vulputate felis rutrum eu.</p>
						<p>Curabitur facilisis luctus cursus. In ultrices ultrices ante, efficitur efficitur velit maximus blandit. Donec finibus ultrices arcu id scelerisque. Pellentesque ante lectus, feugiat ut sodales nec, faucibus sed nisi. In ornare ultricies euismod. Aenean vehicula velit orci, non mattis dui aliquam at. Nullam a ipsum eu orci hendrerit viverra. Curabitur justo odio, tristique nec ligula sed, tristique auctor mi.</p>

					</div>
				</div>
			</div>

		<!-- Footer -->
			<div id="footer">
				<div class="wrapper style2">
					<div class="inner">
						<header class="major">
							<h2>Get in touch</h2>
							<p>Sed egestas, ante et vulputate volutpat pede semper est, vitae luctus metus libero eu augue. Morbi purus libero, faucibus adipiscing, commodo quis, gravida id, est. Sed lectus. Praesent elementum lorem ipsum dolor sit amet consequat hendrerit tortor semper lorem at felis.</p>
						</header>
						<div class="content">
							<div class="form">
								<form method="post" action="#">
									<div class="fields">
										<div class="field half">
											<input name="name" id="name" placeholder="Name" type="text" />
										</div>
										<div class="field half">
											<input name="email" id="email" placeholder="Email" type="email" />
										</div>
										<div class="field">
											<textarea name="message" id="message" rows="6" placeholder="Message"></textarea>
										</div>
									</div>
									<ul class="actions special">
										<li><input type="button" class="button" value="Send Message" /></li>
									</ul>
								</form>
							</div>
							<ul class="icons">
								<li>
									<span class="icon solid fa-home"></span>
									<div>
										<strong>Address</strong>
										1234 Somewhere Road #543<br />
										Nashville, TN 00000
									</div>
								</li>
								<li>
									<span class="icon solid fa-envelope"></span>
									<div>
										<strong>Email</strong>
										<a href="mailto:information@domain.ext">information@domain.ext</a>
									</div>
								</li>
								<li>
									<span class="icon solid fa-phone"></span>
									<div>
										<strong>Phone</strong>
										(000) 000-0000 ext 0000
									</div>
								</li>
							</ul>
						</div>
					</div>
					<div class="copyright">
						&copy; Untitled. All rights reserved. Lorem ipsum dolor sit amet.
					</div>
				</div>
			</div>

		<!-- Scripts -->
			<script src="/static/assets/js/jquery.min.js"></script>
			<script src="/static/assets/js/jquery.dropotron.min.js"></script>
			<script src="/static/assets/js/browser.min.js"></script>
			<script src="/static/assets/js/breakpoints.min.js"></script>
			<script src="/static/assets/js/util.js"></script>
			<script src="/static/assets/js/main.js"></script>

	</body>
</html>

MANGO_ROOT/user/templates/join.html
{% extends 'base.html' %}
{% block title %}회원가입{% endblock  %}
{% block banner %}
<div id="banner">
    <div class="wrapper style1 special">
        <div class="inner">
            <h1 class="heading alt" style="font-family: 'Dongle', sans-serif;">회 원 가 입</h1>
        </div>
    </div>
</div>
{% endblock  %}
{% block contents %}
<div class="inner" style='margin: 5rem 20rem'>
    <form method="post" action="{% url 'User:join' %}">
        {% csrf_token %}
        {{form.as_p}}
        <button class='button primary fit'>작성 완료</button>
    </form>
</div>
{% endblock %}
{% block script %}
<script>
    $(document).ready(function(){

        id_flag = false
        pw_flag = false
        repw_flag = false

        // 아이디 중복검사
        // .attr({'data-bs-original-title': '중복된 아이디입니다.'}).tooltip("show");
        $('#id_userid').focus(function(){
            id_flag = false
        })
        $('#id_userid').change(function(){
            id = $('#id_userid').val().trim()
            if(id.length < 5){
                $('label[for=id_userid]').html('아이디: 최소 5글자 이상 입니다.').css({'color': 'red'})
                id_flag = false
            }
            else{
                $.ajax({
                    url: "{% url 'User:checkid' %}",
                    data: {'userid': id},
                    datatype:'json',
                    success: function(response){
                        if(response.data == 'not exist'){
                            $('label[for=id_userid]').html('아이디: 사용 가능한 아이디 입니다.').css({'color': 'green'})
                            id_flag = true
                            return;
                        }else{
                            $('label[for=id_userid]').html('아이디: 중복된 아이디 입니다.').css({'color': 'red'})
                            id_flag = false
                            return;
                        }
                    }
                })
            }
        })
        // 비밀번호 검사
        $('#id_password').focus(function(){
            pw_flag = false
            repw_flag = false
        })
        $('#id_password').change(function(){
            pw = $(this).val().trim()
            if(!/^(?=.*[A-Za-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$/.test(pw)){
                $('label[for=id_password]').html('비밀번호: 유효하지 않은 비밀번호 입니다.').css({'color': 'red'})
                pw_flag = false
            }else{
                $('label[for=id_password]').html('비밀번호: 사용 가능한 비밀번호 입니다.').css({'color': 'green'})
                pw_flag = true
            }

            repw = $("#id_re_password").val().trim()
            if(pw != repw){
                $('label[for=id_re_password]').html('비밀번호 확인: 비밀번호가 일치하지 않습니다.').css({'color': 'red'})
                repw_flag = false
            }else{
                $('label[for=id_re_password]').html('비밀번호 확인: 확인되었습니다.').css({'color': 'green'})
                repw_flag = true
            }
        })
        // 비밀번호 확인 검사
        $('#id_re_password').focus(function(){
            pw_flag = false
            repw_flag = false
        })
        $('#id_re_password').change(function(){
            repw = $(this).val().trim()
            if(pw != repw){
                $('label[for=id_re_password]').html('비밀번호 확인: 비밀번호가 일치하지 않습니다.').css({'color': 'red'})
                repw_flag = false
            }else{
                $('label[for=id_re_password]').html('비밀번호 확인: 확인되었습니다.').css({'color': 'green'})
                repw_flag = true
            }
        })

        // 취향
        $('input[name=prefer]').change(function(){
            if($(this).is(':checked')){
                $(this).parents('label').css({'color': '#ff8b77'})
            }else{
                $(this).parents('label').css({'color': '#424242'})
            }
        })
    })
</script>
<style>
    ul#id_prefer{
        width:100%;
        list-style: none;
    }
    ul#id_prefer li{
        float:left;
        margin: 0 1%;
    }
    .checked{
        color:#ff8b77;
    }
</style>
{% endblock  %}

MANGO_ROOT/user/templates/login.html
{% extends "base.html" %}

{% block title %}login{% endblock  %}

{% block banner %}
<div id="banner">
    <div class="wrapper style1 special">
        <div class="inner">
            <h1 class="heading alt" style="font-family: 'Dongle', sans-serif;">로 그 인  /  회 원 가 입</h1>
        </div>
    </div>
</div>
{% endblock  %}

{% block contents %}
<div class="inner" style='margin: 5rem 20rem'>
    <form method="post" action="{% url 'User:login' %}">
        {% csrf_token %}
        <div class="fields">
            <div class="field">
                <input name="userid" id="userid" placeholder="아이디" type="text" />
            </div>
            <div class="field">
                <input name="password" id="password" placeholder="비밀번호" type="password" />
            </div>
        </div>
        <ul class="actions special">
            <li><input type="submit" class="button fit" value="로그인" /></li>
            <li><a href="{% url 'User:join' %}" class="button fit">회원가입</a></li>
        </ul>
    </form>
</div>
{% endblock %}


{% block script %}
{% endblock  %}